"""v2 data preparation (separate copies; v1 caches untouched).
 1. split manifest: TRAIN = S1 id%5 in {2,3,4}, DEV = id%5==0, CONF = id%5==1
 2. Indic dictionary re-learned from TRAIN-fold pairs only
 3. v2train_* / v2test_* normalized tables with the new dictionary applied
 4. candidate dirs copied, Indic-script queries re-retrieved (S1 index unchanged)"""
import json
import shutil
from collections import Counter, defaultdict

import polars as pl

from runlib import RUNS, Run, cache_path, mem, note
import apply_indic_dict
import candidates

run = Run("v2_data", {"split": "id%5: 0=DEV 1=CONF 2-4=TRAIN", "dict_min_count": 3, "dict_min_share": 0.6})

# ---- 1. split manifest
if not run.done("split"):
    s1 = pl.read_parquet(cache_path("train_source1.parquet"), columns=["entity_id", "country"]).with_row_index("s1_idx")
    s1 = s1.with_columns((pl.col("entity_id").str.slice(3).cast(pl.Int64) % 5).alias("m5")).with_columns(
        pl.when(pl.col("m5") == 0).then(pl.lit("DEV")).when(pl.col("m5") == 1).then(pl.lit("CONF")).otherwise(pl.lit("TRAIN")).alias("fold"))
    run.write_parquet(s1.select("s1_idx", "entity_id", "country", "fold"), "split_s1.parquet")
    print(s1.group_by("fold").len())
    run.complete("split", files=["split_s1.parquet"])
split = pl.read_parquet(run.path("split_s1.parquet"))

# ---- 2. dictionary from TRAIN fold only
if not run.done("dict"):
    s1n = pl.read_parquet(cache_path("train_source1_norm.parquet"), columns=["entity_id", "name_norm"])
    q_tables = []
    for s in ("source2", "source3"):
        q_src = pl.read_parquet(cache_path(f"train_{s}_norm.parquet"))
        name_col = "name_norm_raw" if "name_norm_raw" in q_src.columns else "name_norm"
        q_tables.append(q_src.filter(pl.col("has_indic"))
                        .select("entity_id", pl.col(name_col).alias("name_norm")))
    q = pl.concat(q_tables)
    gt = (pl.read_parquet(cache_path("train_ground_truth.parquet")).filter(pl.col("matched_entity_ids") != "")
          .with_columns(pl.col("matched_entity_ids").str.split(",")).explode("matched_entity_ids"))
    gt = gt.join(split.filter(pl.col("fold") == "TRAIN").select(pl.col("entity_id").alias("source1_entity_id")), on="source1_entity_id", how="semi")
    pairs = q.join(gt, left_on="entity_id", right_on="matched_entity_ids").join(s1n, left_on="source1_entity_id", right_on="entity_id", suffix="_s1")
    pc, tc = Counter(), Counter()
    for a_, b_ in pairs.select("name_norm", "name_norm_s1").iter_rows():
        qt, st = a_.split(), b_.split()
        if len(qt) == len(st):
            for x, y in zip(qt, st):
                tc[x] += 1; pc[(x, y)] += 1
    best = defaultdict(lambda: (None, 0))
    for (x, y), c in pc.items():
        if c > best[x][1]:
            best[x] = (y, c)
    mapping = {x: y for x, (y, c) in best.items() if x != y and c >= 3 and c / tc[x] >= 0.6}
    old = json.load(open(cache_path("indic_token_dict.json"), encoding="utf-8"))
    (run.path("indic_token_dict_v2.json")).write_text(json.dumps(mapping, ensure_ascii=False, indent=0), encoding="utf-8")
    note(f"v2 Indic dictionary from TRAIN fold only: {len(mapping)} entries (v1 fold-A dict: {len(old)}; overlap {len(set(mapping) & set(old))})")
    run.complete("dict", files=["indic_token_dict_v2.json"])
mapping = json.loads(run.path("indic_token_dict_v2.json").read_text(encoding="utf-8"))

# ---- 3. v2 normalized tables
for src_split, dst in (("train", "v2train"), ("test", "v2test")):
    if run.done(f"norm_{dst}"):
        continue
    for s in ("source1", "source2", "source3"):
        shutil.copyfile(cache_path(f"{src_split}_{s}_norm.parquet"), cache_path(f"{dst}_{s}_norm.parquet"))
        shutil.copyfile(cache_path(f"{src_split}_{s}.parquet"), cache_path(f"{dst}_{s}.parquet"))
    apply_indic_dict.apply(dst, mapping)
    run.complete(f"norm_{dst}")

# ---- 4. candidates: copy, then re-retrieve Indic-script queries with the new names
for src_split, dst in (("train", "v2train"), ("test", "v2test")):
    if run.done(f"cands_{dst}"):
        continue
    d = cache_path(f"{dst}_cands")
    if d.exists():
        shutil.rmtree(d)
    shutil.copytree(cache_path(f"{src_split}_cands"), d)
    for m in list(d.glob("patched_*.done")) + list(d.glob("*_patch_*.parquet")):
        m.unlink()  # Indic queries exist only in the old patch file -> regenerated by patch_queries
    candidates.patch_queries(dst)
    n = pl.scan_parquet(str(d / "*.parquet")).select(pl.len()).collect().item()
    note(f"{dst} candidates ready: {n:,} pairs")
    run.complete(f"cands_{dst}", pairs=n)
run.release()
print("v2_prepare done", mem())
